### ISSUE TITLE
CGA Artifacts filter

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/Presets_MiSTer#10]
As it's known, cga had this composite capability that generate more colours:
https://www.youtube.com/watch?v=niKblgZupOc

Not sure if it is feasable to add a preset filter in PCXT core that would generate such extra colours.

**Comment by Kitrinx** [comment]
Filters are not capable of doing such a thing.

**Comment by jsmolina** [comment]
From this article:
https://retrocomputing.stackexchange.com/questions/2595/does-every-retrocomputer-and-console-with-ntsc-composite-output-have-artifact-c

It seems to be just some kind of blurrying that causes two colors to mix into some predictable result.

**Comment by Kitrinx** [comment]
I know how it works, but filters aren't capable of doing it. It's not now, nor never will be part of the filter system, and consequently not presets either. The blurriness of composite is a result of it's 4:1:1 subsampling and the artifact colors are a result of the composite decoder being tricked either intentionally or not, into interpreting luma as chroma.

**Comment by RGarciaLago** [comment]
@Kitrinx given your answer this issue should be Closed as not planned (won’t fix).

**Comment by Kitrinx** [comment]
Closing as it is not possible in the scope of this system.
